language: csharp

script:
  - xbuild /p:Configuration=Debug database-library.sln

before_install:
  - sudo apt-get install nunit-console

before_script:
  - nuget restore database-library.sln

after_script:
  - nunit-console PersonLibrary.Tests/bin/Debug/PersonLibrary.Tests.dll