language: csharp

script:
  - xbuild /p:Configuration=Debug database-library.sln

before_install:
  - sudo apt-get install nunit-console

before_script:
  - nuget restore database-library.sln

after_script:
  - nunit-console Tests/Common.Tests/bin/Debug/Common.Tests.dll
  - nunit-console Tests/Person.Tests/bin/Debug/Person.Tests.dll