language: csharp

script:
  - xbuild /p:Configuration=Debug database-library.sln

before_install:
  - sudo apt-get install nunit-console

before_script:
  - nuget restore database-library.sln

after_script:
  - nunit-console artifacts/debug/tests/models/common.tests/Common.Tests.dll
  - nunit-console artifacts/debug/tests/models/person.tests/Person.Tests.dll