language: csharp
solution: ./project-database-library.sln
 
install:
  - sudo apt-get install nunit-console
  - nuget restore ./project-database-library.sln
 
script:
  - xbuild ./project-database-library.sln
  - nunit-console ./PersonLibrary.Tests/bin/Debug/PersonLibrary.Tests.dll